version: '3'
services:
  jekyll-github:
    image: starefossen/github-pages
    ports:
      - 4000:4000
    volumes:
      - ./:/usr/src/app

    #secret env vars read from running machine:
    # Environment variables with only a key are resolved to their values on the machine Compose is running on, which can be helpful for secret or host-specific values. (https://docs.docker.com/compose/compose-file/#environment)
    environment:
      - JEKYLL_GITHUB_TOKEN